FROM node:24-alpine

# Set working directory inside container
WORKDIR /app

COPY package*.json ./

# Install dependencies with caching
# Using BuildKit mount for npm cache
RUN --mount=type=cache,target=/root/.npm \ 
    npm ci --prefer-offline --no-audit --progress=false

# Copy the rest of your app
COPY . .

# Expose the application port
EXPOSE 3000

# Default command to start the app
CMD ["npm", "start"]
