FROM node:24-alpine

# Set working directory inside container
WORKDIR /app

COPY package*.json ./

# Install dependencies using npm ci
RUN npm ci

# Copy the rest of your app
COPY . .

# Expose the application port
EXPOSE 3000

# Default command to start the app
CMD ["npm", "start"]
